config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  get "forbidden", to: "pages#forbidden"
  resources :articles
  resources :users, except: [:new]
  get "signup", to: "users#new"
  get "login", to: "session#new"
  post "login", to: "session#create"
  get "logout", to: "session#destroy"
  get "up" => "rails/health#show", as: :rails_health_check
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length:{minimum: 6, maximum: 50}
    validates :body, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles, dependent: :destroy
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, uniqueness: {case_sensitive: false}, presence: true, length: {maximum: 105},
    format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_user
    # helper_method :require_user
    def require_user
        if !@_current_user
            flash[:notice] = "Log in first!"
            redirect_to login_path 
        end
    end
    
    private
    def current_user
      @_current_user ||= session[:current_user_id] &&
        User.find_by(id: session[:current_user_id])
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_user, except: [:index, :show]
    before_action :set_article, only: [:show, :update, :edit, :destroy]
    before_action :require_same_user, only: [:edit, :update,:destroy]
    def index
        # @articles = Article.all
        @articles = Article.paginate(page: params[:page], per_page: 5) 
    end
    def new
        @article = Article.new()
    end
    def create 
        @article = Article.new(article_params)
        @article.user = @_current_user
        if @article.save
            flash[:notice] = "Article was created Successfully"
            redirect_to @article
        else 
            render 'new'
        end
    end
    def show
        @article = Article.find(params[:id])
    end
    def edit
        @article = Article.find(params[:id])
    end
    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        redirect_to @article
    end
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private
    def set_article
        @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :body)
    end
    def require_same_user
        if !@_current_user.admin  && @_current_user.id != @article.user_id
            redirect_to "/forbidden"
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end  
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
       @user = User.new
    end

    def create
        user = User.find_by(username: params[:username])
        # binding.break
        if user && user.authenticate(params[:password])
            flash[:notice] = "Logged in succesfully"
          # Save the user ID in the session so it can be used in
          # subsequent requests
          session[:current_user_id] = user.id
          redirect_to root_url
        end
      end

    def destroy
        # Remove the user id from the session
        session.delete(:current_user_id)
        # Clear the memoized current user
        @_current_user = nil
        redirect_to root_url, status: :see_other
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_user, except: [:index, :show, :new, :create]
    before_action :set_user, only: [:show, :update, :edit, :destroy]
    before_action :require_same_user, only: [:edit, :update,:destroy]
    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "User #{@user.username} created succesfully"
            session[:current_user_id] = @user.id
            redirect_to root_path
        else 
            render 'new'
        end
    end

    def new
        redirect_to "/"  if @_current_user
        @user = User.new()
    end
    
    def show
    end

    def edit    
    end

    def update
        @user.update(user_params)
        # flash[:success] = "user data updated succesfully"
        redirect_to @user
    end

    def destroy
        @user.destroy
        flash[:notice] = "User Account along with all his articles are deleted succesfully"
        if !@_current_user.admin?
            session.delete(:current_user_id)
            # Clear the memoized current user
            @_current_user = nil
            redirect_to root_url, status: :see_other
            return
        end
        redirect_to users_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    def set_user
        @user = User.find(params[:id])
    end
    def require_same_user
        if !@_current_user.admin  && @_current_user.id != @user.id
            redirect_to "/forbidden"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <ul>
        <% @article.errors.full_messages.each do |error_msg| %>
            <li><%= error_msg %></li>
        <% end %>     
    </ul>
<% end %>
<%= form_with(model: @article, local: true, data:{ turbo:false }) do |form| %>
    <p>
        <%= form.label :title%></br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :body%></br>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/edit.html.erb
<%= render 'articles/form' %>

app/views/articles/index.html.erb
<h2><%= link_to 'create a new article', new_article_path %></h2>
<%= will_paginate @articles %>
<table class="table">
<thead> 
    <tr>
    <th scope="col">article_id</th>
    <th scope="col">user_id</th>
    <th scope="col">title</th>
    <th scope="col">body</th>
    <th scope="col">created_at</th>
    <th scope="col">updated_at</th>
    <th scope="col">actions</th>
    </tr>
</thead>
<tbody>
    <% @articles.each do |article| %>
        <tr>
        <th scope="row"><%= article.id %></th>
        <td><%= article.user_id %></td>
        <td><%= article.title %></td>
        <td><%= article.body %></td>
        <td><%= article.created_at %></td>
        <td><%= article.updated_at %></td>
        <td>
        <%= link_to 'show', article_path(article) %>
        <%  if @_current_user && (@_current_user.admin || @_current_user.id == article.user_id) %>
            <%= link_to 'edit', edit_article_path(article) %>
            <%= button_to 'delete', article_path(article), method: :delete %>
        <% end %>
        </td>
        </tr>
    <% end %>
</tbody>
</table>

app/views/articles/new.html.erb
<% if @article.errors.any? %>
    <ul>
        <% @article.errors.full_messages.each do |error_msg| %>
            <li><%= error_msg %></li>
        <% end %>     
    </ul>
<% end %>
<%= render 'articles/form' %>

app/views/articles/show.html.erb
title: <%= @article.title %> <br/>
body: <%= @article.body %> <br/>
<% if @article.user %>
   created_by: <%= @article.user.username  %> <br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body >
    <%= render '/navbar' %>
    <div class="enclosure">
      <div class="enclosure">
        <% flash.each do |name, msg| %> 
          <%= msg %> 
        <% end %>
      </div>
      <%= yield %>
    </div>
    
    <%= render '/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to About page!</h1>

app/views/pages/forbidden.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>forbidden</title>
</head>
<body>
    No Authorization Error Page!
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbo-container">
    <div class="jumbotron text-center">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <p class="lead">
    <%= (link_to 'Sign Up', signup_path, class: "btn btn-success btn-lg") if !@_current_user %>
    </p>
    </div>
</div>

app/views/session/new.html.erb
<div class="enclosure">
   <%= form_with(url: "/login", method: :post) do |form| %>
        <p>
            <%= form.label :username%>
            <%= form.text_field :username %>
        </p>
        <p>
            <%= form.label :password%>
            <%= form.password_field :password %>
        </p>
        <p>
            <%= form.submit "Login" %>
        </p>
   <% end %>
</div>

app/views/users/_auth_form.html.erb
<% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |error_msg| %>
            <li><%= error_msg %></li>
        <% end %>     
    </ul>
<% end %>
<%= form_with(model: @user, local: true, data:{ turbo:false }) do |form| %>
    <p>
        <%= form.label :username %></br>
        <%= form.text_field :username %>
    </p>
    <p>
        <%= form.label :email%></br>
        <%= form.email_field :email %>
    </p>
    <p>
        <%= form.label :password%></br>
        <%= form.password_field :password %>
    </p>
    <p>
        <%= form.submit(@user.new_record? ? "Sign Up" : "Update Account") %>
    </p>
<% end %>

app/views/users/edit.html.erb
<%= render '/users/auth_form' %>

app/views/users/index.html.erb
<h2><%= link_to 'create a new article', new_article_path %></h2>
<%= will_paginate @users %>
<table class="table">
<thead> 
    <tr>
    <th scope="col">user_id</th>
    <th scope="col">username</th>
    <th scope="col">email</th>
    <th scope="col">created_at</th>
    <th scope="col">updated_at</th>
    <th scope="col">actions</th>
    </tr>
</thead>
<tbody>
    <% @users.each do |user| %>
        <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td>
            <%= link_to 'show', user_path(user) %>
            <% if @_current_user && (@_current_user.admin || @_current_user.id == user.id) %>
                <%= link_to 'edit', edit_user_path(user) %>
                <%= button_to 'delete', user_path(user), method: :delete %>
            <% end %>
        </td>
        </tr>
    <% end %>
</tbody>
</table>

app/views/users/new.html.erb
<%= render '/users/auth_form' %>

app/views/users/show.html.erb
<p><strong>username:</strong> <%= @user[:username] %></p> <br/>
<p><strong>email:</strong> <%= @user[:email] %></p><br/>
<h3>Articles corresponding to <%= @user[:username] %></h3>
<ul>
    <% @user.articles.each do |article| %>
        <li>
            title: <%= article.title %> <br/>
            body: <%= article.body %> <br/>             
            <% if article.user %>
                created_by: <%= article.user.username %> <br/>
            <% end %>
        </li>
        <br/>
    <% end %>
</ul>